<?php
//ESSE CONTROLER MANTEMOS DADOS BASICOS DE TODAS AS PÁGINA
//EM CADA CONTROLLER DO SISTEMA, OS DADOS BÁSICOS SÃO SOBREEESCITOS PARA
//SATISFAZER AS NECESSIDADES DA PÁGINA.


//TODAS AS DEFINIÇÕES DE SEO ACONTECEM NO CONTROLLER
$titulo_pagina = 'Jogo Manu - Conteúdo Para Ensino Fundamental E Ensino Médido';

//PARTES FIXAS DA PÁGINA
$parte = 'centro_home.php';
